import React, { Component } from 'react';
// import SearchBar from './SearchBar.js';
import DrawLineChart from './DrawLineChart';
import DrawBarChart from './DrawBarChart';
import DrawTreeChart from './DrawTreeChart';
// import './RenderedChart.css';
// import Level1JobData from './Level1JobData';
// import LoadCsvData from './LoadCsvData';


class RenderedChart extends Component {
  state = {  
    data: []
  }

  componentDidMount() {
    const data = [
      {
        "index": 2,
        "fulltitle": "Management occupations",
        "title": "Management",
        "hierarchy": 1,
        "jobtype": "Summary",
        "jobs2016": 9533.1,
        "jobs2026": 10340.4,
        "delta_num": 807.3,
        "delta_perc": 8.5,
        "perc_self_employed_2016": 19.8,
        "annual_avg_openings_2016-26": 841.5,
        "med_annual_wage_2017": 102590,
        "entry_ed_req": "NA",
        "work_exp": "NA",
        "otj_training_to_competency": "NA",
        "ttl": "Management occupations",
        "Level0": "Jobs",
        "Level1": "Management occupations",
        "Level2": "NA",
        "Level3": "NA",
        "Level4": "NA",
        "pathString": "Jobs/Management occupations/NA/NA/NA"
      },
      {
        "index": 43,
        "fulltitle": "Business & financial operations occupations",
        "title": "Business/Finance",
        "hierarchy": 1,
        "jobtype": "Summary",
        "jobs2016": 8066.8,
        "jobs2026": 8840.7,
        "delta_num": 773.8,
        "delta_perc": 9.6,
        "perc_self_employed_2016": 5.5,
        "annual_avg_openings_2016-26": 817.7,
        "med_annual_wage_2017": 67710,
        "entry_ed_req": "NA",
        "work_exp": "NA",
        "otj_training_to_competency": "NA",
        "ttl": "Business & financial operations occupations",
        "Level0": "Jobs",
        "Level1": "Business & financial operations occupations",
        "Level2": "Other management occupations",
        "Level3": "Managers, all other",
        "Level4": "Education administrators, all other",
        "pathString": "Jobs/Business & financial operations occupations/Other management occupations/Managers, all other/Education administrators, all other"
      },
      {
        "index": 84,
        "fulltitle": "Computer & mathematical occupations",
        "title": "Computer/Math",
        "hierarchy": 1,
        "jobtype": "Summary",
        "jobs2016": 4419,
        "jobs2026": 5026.5,
        "delta_num": 607.5,
        "delta_perc": 13.7,
        "perc_self_employed_2016": 2.6,
        "annual_avg_openings_2016-26": 366.8,
        "med_annual_wage_2017": 84560,
        "entry_ed_req": "NA",
        "work_exp": "NA",
        "otj_training_to_competency": "NA",
        "ttl": "Computer & mathematical occupations",
        "Level0": "Jobs",
        "Level1": "Computer & mathematical occupations",
        "Level2": "Financial specialists",
        "Level3": "Financial specialists, all other",
        "Level4": "Tax preparers",
        "pathString": "Jobs/Computer & mathematical occupations/Financial specialists/Financial specialists, all other/Tax preparers"
      },
      {
        "index": 111,
        "fulltitle": "Architecture & engineering occupations",
        "title": "Architecture/Engineering",
        "hierarchy": 1,
        "jobtype": "Summary",
        "jobs2016": 2601,
        "jobs2026": 2795.4,
        "delta_num": 194.3,
        "delta_perc": 7.5,
        "perc_self_employed_2016": 2.7,
        "annual_avg_openings_2016-26": 210.1,
        "med_annual_wage_2017": 79180,
        "entry_ed_req": "NA",
        "work_exp": "NA",
        "otj_training_to_competency": "NA",
        "ttl": "Architecture & engineering occupations",
        "Level0": "Jobs",
        "Level1": "Architecture & engineering occupations",
        "Level2": "Mathematical science occupations",
        "Level3": "Miscellaneous mathematical science occupations",
        "Level4": "Mathematical science occupations, all other",
        "pathString": "Jobs/Architecture & engineering occupations/Mathematical science occupations/Miscellaneous mathematical science occupations/Mathematical science occupations, all other"
      },
      {
        "index": 156,
        "fulltitle": "Life, physical, & social science occupations",
        "title": "Life/Physical/Social Science",
        "hierarchy": 1,
        "jobtype": "Summary",
        "jobs2016": 1299.5,
        "jobs2026": 1424.3,
        "delta_num": 124.8,
        "delta_perc": 9.6,
        "perc_self_employed_2016": 4.9,
        "annual_avg_openings_2016-26": 132.8,
        "med_annual_wage_2017": 64510,
        "entry_ed_req": "NA",
        "work_exp": "NA",
        "otj_training_to_competency": "NA",
        "ttl": "Life, physical, etc",
        "Level0": "Jobs",
        "Level1": "Life, physical, etc",
        "Level2": "Drafters, engineering technicians, etc",
        "Level3": "Surveying & mapping technicians",
        "Level4": "Engineering technicians, except drafters, etc",
        "pathString": "Jobs/Life, physical, etc/Drafters, engineering technicians, etc/Surveying & mapping technicians/Engineering technicians, except drafters, etc"
      },
      {
        "index": 214,
        "fulltitle": "Community & social service occupations",
        "title": "Community/Social Service",
        "hierarchy": 1,
        "jobtype": "Summary",
        "jobs2016": 2570.7,
        "jobs2026": 2942.6,
        "delta_num": 371.9,
        "delta_perc": 14.5,
        "perc_self_employed_2016": 2.6,
        "annual_avg_openings_2016-26": 330.7,
        "med_annual_wage_2017": 43840,
        "entry_ed_req": "NA",
        "work_exp": "NA",
        "otj_training_to_competency": "NA",
        "ttl": "Community & social service occupations",
        "Level0": "Jobs",
        "Level1": "Community & social service occupations",
        "Level2": "Life, physical, etc",
        "Level3": "Miscellaneous life, physical, etc",
        "Level4": "Life, physical, etc",
        "pathString": "Jobs/Community & social service occupations/Life, physical, etc/Miscellaneous life, physical, etc/Life, physical, etc"
      },
      {
        "index": 238,
        "fulltitle": "Legal occupations",
        "title": "Legal",
        "hierarchy": 1,
        "jobtype": "Summary",
        "jobs2016": 1283.3,
        "jobs2026": 1399.5,
        "delta_num": 116.2,
        "delta_perc": 9.1,
        "perc_self_employed_2016": 14.4,
        "annual_avg_openings_2016-26": 90.8,
        "med_annual_wage_2017": 80080,
        "entry_ed_req": "NA",
        "work_exp": "NA",
        "otj_training_to_competency": "NA",
        "ttl": "Legal occupations",
        "Level0": "Jobs",
        "Level1": "Legal occupations",
        "Level2": "Religious workers",
        "Level3": "Religious workers, all other",
        "Level4": "Community & social service specialists, all other",
        "pathString": "Jobs/Legal occupations/Religious workers/Religious workers, all other/Community & social service specialists, all other"
      },
      {
        "index": 253,
        "fulltitle": "Education, training, & library occupations",
        "title": "Education/Training/Library",
        "hierarchy": 1,
        "jobtype": "Summary",
        "jobs2016": 9426.5,
        "jobs2026": 10315.4,
        "delta_num": 888.9,
        "delta_perc": 9.4,
        "perc_self_employed_2016": 1.9,
        "annual_avg_openings_2016-26": 918.5,
        "med_annual_wage_2017": 48740,
        "entry_ed_req": "NA",
        "work_exp": "NA",
        "otj_training_to_competency": "NA",
        "ttl": "Education, training, etc",
        "Level0": "Jobs",
        "Level1": "Education, training, etc",
        "Level2": "Legal support workers",
        "Level3": "Miscellaneous legal support workers",
        "Level4": "Legal support workers, all other",
        "pathString": "Jobs/Education, training, etc/Legal support workers/Miscellaneous legal support workers/Legal support workers, all other"
      },
      {
        "index": 337,
        "fulltitle": "Arts, design, entertainment, sports, & media occupations",
        "title": "Arts/Design/Entertainment/Sports/Media",
        "hierarchy": 1,
        "jobtype": "Summary",
        "jobs2016": 2772.9,
        "jobs2026": 2941,
        "delta_num": 168.1,
        "delta_perc": 6.1,
        "perc_self_employed_2016": 25.2,
        "annual_avg_openings_2016-26": 288.9,
        "med_annual_wage_2017": 48230,
        "entry_ed_req": "NA",
        "work_exp": "NA",
        "otj_training_to_competency": "NA",
        "ttl": "Arts, design, etc",
        "Level0": "Jobs",
        "Level1": "Arts, design, etc",
        "Level2": "Other education, training, etc",
        "Level3": "Education, training, etc",
        "Level4": "Museum technicians & conservators",
        "pathString": "Jobs/Arts, design, etc/Other education, training, etc/Education, training, etc/Museum technicians & conservators"
      },
      {
        "index": 395,
        "fulltitle": "Healthcare practitioners & technical occupations",
        "title": "Healthcare/Technical",
        "hierarchy": 1,
        "jobtype": "Summary",
        "jobs2016": 8751.5,
        "jobs2026": 10088.1,
        "delta_num": 1336.6,
        "delta_perc": 15.3,
        "perc_self_employed_2016": 2.7,
        "annual_avg_openings_2016-26": 625.1,
        "med_annual_wage_2017": 64770,
        "entry_ed_req": "NA",
        "work_exp": "NA",
        "otj_training_to_competency": "NA",
        "ttl": "Healthcare practitioners & technical occupations",
        "Level0": "Jobs",
        "Level1": "Healthcare practitioners & technical occupations",
        "Level2": "Media & communication equipment workers",
        "Level3": "Media & communication equipment workers, all other",
        "Level4": "Film & video editors",
        "pathString": "Jobs/Healthcare practitioners & technical occupations/Media & communication equipment workers/Media & communication equipment workers, all other/Film & video editors"
      },
      {
        "index": 469,
        "fulltitle": "Healthcare support occupations",
        "title": "Healthcare Support",
        "hierarchy": 1,
        "jobtype": "Summary",
        "jobs2016": 4315.6,
        "jobs2026": 5335.2,
        "delta_num": 1019.6,
        "delta_perc": 23.6,
        "perc_self_employed_2016": 2.8,
        "annual_avg_openings_2016-26": 638.4,
        "med_annual_wage_2017": 28710,
        "entry_ed_req": "NA",
        "work_exp": "NA",
        "otj_training_to_competency": "NA",
        "ttl": "Healthcare support occupations",
        "Level0": "Jobs",
        "Level1": "Healthcare support occupations",
        "Level2": "Other healthcare practitioners & technical occupations",
        "Level3": "Miscellaneous health practitioners & technical workers",
        "Level4": "Healthcare practitioners & technical workers, all other",
        "pathString": "Jobs/Healthcare support occupations/Other healthcare practitioners & technical occupations/Miscellaneous health practitioners & technical workers/Healthcare practitioners & technical workers, all other"
      },
      {
        "index": 493,
        "fulltitle": "Protective service occupations",
        "title": "Protective Service",
        "hierarchy": 1,
        "jobtype": "Summary",
        "jobs2016": 3505.6,
        "jobs2026": 3663.8,
        "delta_num": 158.2,
        "delta_perc": 4.5,
        "perc_self_employed_2016": 0.5,
        "annual_avg_openings_2016-26": 397.2,
        "med_annual_wage_2017": 39550,
        "entry_ed_req": "NA",
        "work_exp": "NA",
        "otj_training_to_competency": "NA",
        "ttl": "Protective service occupations",
        "Level0": "Jobs",
        "Level1": "Protective service occupations",
        "Level2": "Other healthcare support occupations",
        "Level3": "Miscellaneous healthcare support occupations",
        "Level4": "Healthcare support workers, all other",
        "pathString": "Jobs/Protective service occupations/Other healthcare support occupations/Miscellaneous healthcare support occupations/Healthcare support workers, all other"
      },
      {
        "index": 526,
        "fulltitle": "Food preparation & serving related occupations",
        "title": "Food/Service",
        "hierarchy": 1,
        "jobtype": "Summary",
        "jobs2016": 13206.1,
        "jobs2026": 14438.1,
        "delta_num": 1232,
        "delta_perc": 9.3,
        "perc_self_employed_2016": 0.5,
        "annual_avg_openings_2016-26": 2469.9,
        "med_annual_wage_2017": 21910,
        "entry_ed_req": "NA",
        "work_exp": "NA",
        "otj_training_to_competency": "NA",
        "ttl": "Food preparation & serving related occupations",
        "Level0": "Jobs",
        "Level1": "Food preparation & serving related occupations",
        "Level2": "Other protective service workers",
        "Level3": "Miscellaneous protective service workers",
        "Level4": "Protective service workers, all other",
        "pathString": "Jobs/Food preparation & serving related occupations/Other protective service workers/Miscellaneous protective service workers/Protective service workers, all other"
      },
      {
        "index": 551,
        "fulltitle": "Building & grounds cleaning & maintenance occupations",
        "title": "Building/Grounds Maintenance",
        "hierarchy": 1,
        "jobtype": "Summary",
        "jobs2016": 5654.1,
        "jobs2026": 6177.9,
        "delta_num": 523.8,
        "delta_perc": 9.3,
        "perc_self_employed_2016": 12.4,
        "annual_avg_openings_2016-26": 788.4,
        "med_annual_wage_2017": 25620,
        "entry_ed_req": "NA",
        "work_exp": "NA",
        "otj_training_to_competency": "NA",
        "ttl": "Building & grounds cleaning & maintenance occupations",
        "Level0": "Jobs",
        "Level1": "Building & grounds cleaning & maintenance occupations",
        "Level2": "Other food preparation & serving related workers",
        "Level3": "Food preparation & serving related workers, all other",
        "Level4": "Counter attendants, cafeteria, etc",
        "pathString": "Jobs/Building & grounds cleaning & maintenance occupations/Other food preparation & serving related workers/Food preparation & serving related workers, all other/Counter attendants, cafeteria, etc"
      },
      {
        "index": 566,
        "fulltitle": "Personal care & service occupations",
        "title": "Personal Care/Service",
        "hierarchy": 1,
        "jobtype": "Summary",
        "jobs2016": 6419.7,
        "jobs2026": 7647.4,
        "delta_num": 1227.6,
        "delta_perc": 19.1,
        "perc_self_employed_2016": 16.2,
        "annual_avg_openings_2016-26": 1140.9,
        "med_annual_wage_2017": 23610,
        "entry_ed_req": "NA",
        "work_exp": "NA",
        "otj_training_to_competency": "NA",
        "ttl": "Personal care & service occupations",
        "Level0": "Jobs",
        "Level1": "Personal care & service occupations",
        "Level2": "Grounds maintenance workers",
        "Level3": "Grounds maintenance workers, all other",
        "Level4": "Building cleaning workers, all other",
        "pathString": "Jobs/Personal care & service occupations/Grounds maintenance workers/Grounds maintenance workers, all other/Building cleaning workers, all other"
      },
      {
        "index": 614,
        "fulltitle": "Sales & related occupations",
        "title": "Sales",
        "hierarchy": 1,
        "jobtype": "Summary",
        "jobs2016": 15747.8,
        "jobs2026": 16206.5,
        "delta_num": 458.7,
        "delta_perc": 2.9,
        "perc_self_employed_2016": 7.8,
        "annual_avg_openings_2016-26": 2201.1,
        "med_annual_wage_2017": 27020,
        "entry_ed_req": "NA",
        "work_exp": "NA",
        "otj_training_to_competency": "NA",
        "ttl": "Sales & related occupations",
        "Level0": "Jobs",
        "Level1": "Sales & related occupations",
        "Level2": "Other personal care & service workers",
        "Level3": "Personal care & service workers, all other",
        "Level4": "Recreation workers",
        "pathString": "Jobs/Sales & related occupations/Other personal care & service workers/Personal care & service workers, all other/Recreation workers"
      },
      {
        "index": 647,
        "fulltitle": "Office & administrative support occupations",
        "title": "Office/Administrative",
        "hierarchy": 1,
        "jobtype": "Summary",
        "jobs2016": 23081.2,
        "jobs2026": 23230.8,
        "delta_num": 149.6,
        "delta_perc": 0.6,
        "perc_self_employed_2016": 1,
        "annual_avg_openings_2016-26": 2596.4,
        "med_annual_wage_2017": 34740,
        "entry_ed_req": "NA",
        "work_exp": "NA",
        "otj_training_to_competency": "NA",
        "ttl": "Office & administrative support occupations",
        "Level0": "Jobs",
        "Level1": "Office & administrative support occupations",
        "Level2": "Other sales & related workers",
        "Level3": "Miscellaneous sales & related workers",
        "Level4": "Sales & related workers, all other",
        "pathString": "Jobs/Office & administrative support occupations/Other sales & related workers/Miscellaneous sales & related workers/Sales & related workers, all other"
      },
      {
        "index": 714,
        "fulltitle": "Farming, fishing, & forestry occupations",
        "title": "Farming/Fishing/Forestry",
        "hierarchy": 1,
        "jobtype": "Summary",
        "jobs2016": 1060.1,
        "jobs2026": 1056.7,
        "delta_num": -3.5,
        "delta_perc": -0.3,
        "perc_self_employed_2016": 4,
        "annual_avg_openings_2016-26": 154.3,
        "med_annual_wage_2017": 24390,
        "entry_ed_req": "NA",
        "work_exp": "NA",
        "otj_training_to_competency": "NA",
        "ttl": "Farming, fishing, etc",
        "Level0": "Jobs",
        "Level1": "Farming, fishing, etc",
        "Level2": "Other office & administrative support workers",
        "Level3": "Office & administrative support workers, all other",
        "Level4": "Word processors & typists",
        "pathString": "Jobs/Farming, fishing, etc/Other office & administrative support workers/Office & administrative support workers, all other/Word processors & typists"
      },
      {
        "index": 734,
        "fulltitle": "Construction & extraction occupations",
        "title": "Construction/Extraction",
        "hierarchy": 1,
        "jobtype": "Summary",
        "jobs2016": 6812.5,
        "jobs2026": 7560,
        "delta_num": 747.6,
        "delta_perc": 11,
        "perc_self_employed_2016": 17.5,
        "annual_avg_openings_2016-26": 798.1,
        "med_annual_wage_2017": 44730,
        "entry_ed_req": "NA",
        "work_exp": "NA",
        "otj_training_to_competency": "NA",
        "ttl": "Construction & extraction occupations",
        "Level0": "Jobs",
        "Level1": "Construction & extraction occupations",
        "Level2": "Forest, conservation, etc",
        "Level3": "Logging workers",
        "Level4": "Logging workers, all other",
        "pathString": "Jobs/Construction & extraction occupations/Forest, conservation, etc/Logging workers/Logging workers, all other"
      },
      {
        "index": 811,
        "fulltitle": "Installation, maintenance, & repair occupations",
        "title": "Installation/Maintenance/Repair",
        "hierarchy": 1,
        "jobtype": "Summary",
        "jobs2016": 5905.4,
        "jobs2026": 6293.6,
        "delta_num": 388.2,
        "delta_perc": 6.6,
        "perc_self_employed_2016": 5.2,
        "annual_avg_openings_2016-26": 610.6,
        "med_annual_wage_2017": 44520,
        "entry_ed_req": "NA",
        "work_exp": "NA",
        "otj_training_to_competency": "NA",
        "ttl": "Installation, maintenance, etc",
        "Level0": "Jobs",
        "Level1": "Installation, maintenance, etc",
        "Level2": "Extraction workers",
        "Level3": "Extraction workers, all other",
        "Level4": "Mining machine operators, all other",
        "pathString": "Jobs/Installation, maintenance, etc/Extraction workers/Extraction workers, all other/Mining machine operators, all other"
      },
      {
        "index": 879,
        "fulltitle": "Production occupations",
        "title": "Production",
        "hierarchy": 1,
        "jobtype": "Summary",
        "jobs2016": 9356.9,
        "jobs2026": 8950,
        "delta_num": -406.9,
        "delta_perc": -4.3,
        "perc_self_employed_2016": 2.6,
        "annual_avg_openings_2016-26": 990.4,
        "med_annual_wage_2017": 33990,
        "entry_ed_req": "NA",
        "work_exp": "NA",
        "otj_training_to_competency": "NA",
        "ttl": "Production occupations",
        "Level0": "Jobs",
        "Level1": "Production occupations",
        "Level2": "Other installation, maintenance, etc",
        "Level3": "Miscellaneous installation, maintenance, etc",
        "Level4": "Installation, maintenance, etc",
        "pathString": "Jobs/Production occupations/Other installation, maintenance, etc/Miscellaneous installation, maintenance, etc/Installation, maintenance, etc"
      },
      {
        "index": 1023,
        "fulltitle": "Transportation & material moving occupations",
        "title": "Transportation/Material Moving",
        "hierarchy": 1,
        "jobtype": "Summary",
        "jobs2016": 10274.2,
        "jobs2026": 10908.4,
        "delta_num": 634.3,
        "delta_perc": 6.2,
        "perc_self_employed_2016": 4.4,
        "annual_avg_openings_2016-26": 1333.4,
        "med_annual_wage_2017": 31600,
        "entry_ed_req": "NA",
        "work_exp": "NA",
        "otj_training_to_competency": "NA",
        "ttl": "Transportation & material moving occupations",
        "Level0": "Jobs",
        "Level1": "Transportation & material moving occupations",
        "Level2": "Other production occupations",
        "Level3": "Miscellaneous production workers",
        "Level4": "Production workers, all other",
        "pathString": "Jobs/Transportation & material moving occupations/Other production occupations/Miscellaneous production workers/Production workers, all other"
      } 
    ]
    this.setState({data})
  }

  render() { 
    return (  
      <div>
        {/* <SearchBar /> */}
        <DrawTreeChart />
        <DrawLineChart data={this.state.data}/>
        <DrawBarChart data={this.state.data}/>
        {/* <LoadCsvData /> */}
      </div>
    );
  }
}
 
export default RenderedChart;